# NumPy Arrays

In [1]:
#to import numpy array 
import numpy as np
#to check version of numpy package 
print(np.__version__)

1.19.2


In [2]:
#Creating array using array function
from numpy import *
array1 = array([10, 20, 30, 40, 50], dtype = int)
print(array1)
print(array1.dtype)

[10 20 30 40 50]
int32


In [3]:
#to check dataype
int_array = np.array([10, 20, 30, 40, 50])
print(int_array.dtype)

int32


In [4]:
#Creating array using array function

array1 = np.array([10, 20, 30, 40, 50])
print(array1)
print(array1.dtype)

[10 20 30 40 50]
int32


In [5]:
#Creating array using array function

array1 = np.array([10, 20, 30, 40.45, 50], int)
print(array1)
print(array1.dtype)

[10 20 30 40 50]
int32


In [6]:
#Creating multidimesnional array (2-D) using array function

array1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]] )
print(array1)
print(array1.dtype)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
int32


In [7]:
#Creating multidimesnional array (3-D) using array function

array1 = np.array([ [[5, 10, 15], [20, 25, 30]], [[35, 40, 45], [50, 55, 60]] ] )
print(array1)
print(array1.dtype)

[[[ 5 10 15]
  [20 25 30]]

 [[35 40 45]
  [50 55 60]]]
int32


In [8]:
#Creating array using array function

array1 = np.array([10, 20, 30, 40.45, 50])
print(array1)
print(array1.dtype)

[10.   20.   30.   40.45 50.  ]
float64


In [9]:
#Creating array using array function

array1 = np.array([10, 20, 30, 40.45, 50], float)
print(array1)
print(array1.dtype)

[10.   20.   30.   40.45 50.  ]
float64


In [10]:
#Creating array using array function

array1 = np.array(['Ram', 'Shyam', 'Ajay', 'Karan', 'Kunal'], dtype =str)
print(array1)
print(array1.dtype)

['Ram' 'Shyam' 'Ajay' 'Karan' 'Kunal']
<U5


In [11]:
#Creating array using array function

array1 = np.array(['Ram', 'Shyam', 'Ajay', 'Karan', 'Kunal'], str)
print(array1)
print(array1.dtype)

['Ram' 'Shyam' 'Ajay' 'Karan' 'Kunal']
<U5


## creating array using linespace funtion

In [12]:
#Creating array using linspace() function

array1 = np.linspace(1, 50, 5)
print(array1)
print(array1.dtype)

[ 1.   13.25 25.5  37.75 50.  ]
float64


## creating array using logspace() funtion

In [13]:
#Creating array using logspace() function

array1 = np.logspace(1, 5, 5)
print(array1)
print(array1.dtype)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]
float64


## creating array using arange() funtion

In [14]:
#Creating array using arange() function

array1 = np.arange(0, 50, 5)
print(array1)
print(array1.dtype)

[ 0  5 10 15 20 25 30 35 40 45]
int32


## creating array using zeros() funtion

In [15]:
#Creating array using zeros() function

array1 = np.zeros(5, int)
print(array1)
print(array1.dtype)

[0 0 0 0 0]
int32


In [16]:
#Creating array using zeros() function

array1 = np.zeros(5, float)
print(array1)
print(array1.dtype)

[0. 0. 0. 0. 0.]
float64


In [17]:
#Creating array using zeros() function
#Two dimension array
array1 = np.zeros((3,4), int)
print(array1)
print(array1.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


## creating array using ones() funtion

In [18]:
#Creating array using ones() function
#one dimension array
array1 = np.ones(5, int)
print(array1)
print(array1.dtype)

[1 1 1 1 1]
int32


In [19]:
#Creating array using ones() function
#one dimension array
array1 = np.ones(5, float)
print(array1)
print(array1.dtype)

[1. 1. 1. 1. 1.]
float64


In [20]:
#Creating array using ones() function
#two dimension array
array1 = np.ones(5, dtype=int)
print(array1)
print(array1.dtype)

[1 1 1 1 1]
int32


In [21]:
#Creating array using eye() function
#two dimension array
array1 = np.eye(4, dtype =int)
print(array1)
print(array1.dtype)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
int32


In [22]:
#Creating array using zeros() function
#Two dimension array
#reshape()
array1 = np.zeros((5,4), int)
print(array1)
array1.reshape(4,5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Accesing NumPy arrays

In [23]:
#Creating array using array function
#accessing numpy array
import numpy as np
array1 = np.array([10, 20, 30, 40.45, 50], dtype = int)
#access first element or index 0)
print(array1[0])

10


In [24]:
#Creating array using array function
#accessing numpy array
import numpy as np
array1 = np.array([10, 20, 30, 40.45, 50], dtype = int)
#slicing first 2 elements 
print(array1[0:2])

[10 20]


In [25]:
# To access every second element from the slice 
array1 = np.array([10, 20, 30, 40.45, 50], dtype = int)
print(array1[: : 2]) 


[10 30 50]


In [26]:
# To access 2nd element on 1st dimensional array 
array1 = np.array([ [10, 20, 30, 40], [45, 50, 55, 60]])
print(array1[0, 1]) 

20


In [27]:
# To access elements from 2-dimensional array 
array1 = np.array([ [10, 20, 30, 40], [45, 50, 55, 60]])
print(array1[1, 1:3]) 

[50 55]


In [28]:
# 3rd element inside the 1st 1-d array in the 2nd 2-d array 
array1 = np.array([[[10, 20, 30, 40], [50, 60, 70, 80]], [[90, 100, 110, 120], [130, 140, 150, 160]]]) 
print(array1[1, 0, 2]) 

110


In [29]:
#To slice a 3-D Array with an interval of 2. 
array1 = np.array([[[10, 20, 30, 40], [50, 60, 70, 80]], [[90, 100, 110, 120], [130, 140, 150, 160]]]) 
print(array1[1][0][2::3])
print(array1[1][0][3])


[110]
120


In [30]:
#Creating array using array function
#shape of array
import numpy as np
array1 = np.array([10, 20, 30, 40.45, 50], dtype = int)
print(array1.shape)

(5,)


In [31]:
# To shape of an array 
array1 = np.array([ [10, 20, 30, 40], [45, 50, 55, 60]])
print(array1.shape) 

(2, 4)


In [32]:
#reshape of 1-d array to 2-d array
import numpy as np
array1 = np.array([10, 20, 30, 40.45, 50, 60], dtype = int)

print(array1.reshape(2,3))

[[10 20 30]
 [40 50 60]]
